title: XCP
description: Trade Cryptoassets Peer-to-Peer
show_downloads: false
github:
  is_project_page: true
  repository_name: XCP.io
  repository_url: https://github.com/xcp
  owner_name: Dan Anderson
  owner_url: https://github.com/droplister
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
google_analytics: UA-112477384-11