title: XCP
description: Trade Cryptoassets Peer-to-Peer
github:
  is_project_page: true
  repository_name: XCP.io
  repository_url: https://github.com/xcp
  owner_name: Dan Anderson
  owner_url: https://github.com/droplister
show_downloads: false
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag